server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: discovery-server

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always