spring:
  cache:
    type: caffeine
    cache-names: exchangeRates
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h
  application:
    name: currency-service

server:
  port: 0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
