server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: charity-boxes
          uri: lb://charity-service
          predicates:
            - Path=/v1/boxes/**

        - id: charity-events
          uri: lb://charity-service
          predicates:
            - Path=/v1/events/**

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/v1/reports/**